### ISSUE TITLE
Segment fault after module definition when using functions like `puts`

### ISSUE THREAD

**Issue by mitch000001** [goruby/goruby#32]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```shell
GOARCH="amd64"
GOBIN="/Users/mitch/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mitch"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/65/106pnkdj4q158c3xbx9h6ksr0000gn/T/go-build213543851=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What version of GoRuby are you using (`git show -s --format=%H` or goruby -version)?
master (ec0bb1dc93f3edd8253ffedde46ea2f8ebbc8206)

### What did you do?

```shell
$ module_segment_fault=<<EOF
module Foo
end

puts 'hello'
EOF
$ go run main.go -e "${module_segment_fault}"
```

### What did you expect to see?
`hello`

### What did you see instead?
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10bc60d]

goroutine 1 [running]:
github.com/goruby/goruby/object.Send(0x117c540, 0xc420086500, 0xc420082590, 0x4, 0xc4200864f0, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/mitch/src/github.com/goruby/goruby/object/send.go:6 +0x5d
github.com/goruby/goruby/evaluator.Eval(0x123a0c8, 0xc4200980a0, 0x117d760, 0xc4200824e0, 0x0, 0x0, 0x0, 0x0)
	/Users/mitch/src/github.com/goruby/goruby/evaluator/evaluator.go:104 +0xe33
github.com/goruby/goruby/evaluator.Eval(0x123a068, 0xc42007e750, 0x117d760, 0xc4200824e0, 0x0, 0x0, 0x0, 0x0)
	/Users/mitch/src/github.com/goruby/goruby/evaluator/evaluator.go:26 +0x117d
github.com/goruby/goruby/evaluator.evalProgram(0xc4200825c0, 0x2, 0x2, 0x117d760, 0xc4200824e0, 0xc420082580, 0x0, 0x1d, 0x20)
	/Users/mitch/src/github.com/goruby/goruby/evaluator/evaluator.go:147 +0x95
github.com/goruby/goruby/evaluator.Eval(0x117ba40, 0xc4200825a0, 0x117d760, 0xc4200824e0, 0x0, 0x0, 0x0, 0x0)
	/Users/mitch/src/github.com/goruby/goruby/evaluator/evaluator.go:24 +0x278
github.com/goruby/goruby/interpreter.(*interpreter).Interpret(0xc420086260, 0xc420082580, 0x1d, 0x21d, 0xc420082580, 0x1d, 0x0)
	/Users/mitch/src/github.com/goruby/goruby/interpreter/interpreter.go:32 +0xc3
main.main()
	/Users/mitch/src/github.com/goruby/goruby/main.go:53 +0x220
exit status 2
```

**Comment by mitch000001** [comment]
After investigating I found out that the issue lies in the `env.Set`/`env.Unset` of self for the module definition.
